# This file was generated by GoReleaser. DO NOT EDIT.
cask "cc-port-with-logo" do
  version "0.6.0"

  on_macos do
    on_intel do
      sha256 "f609bdd254d08d2af6ac395663d765d1e8ff41946dd03a9afad5a0a35d8bc029"
      url "https://github.com/it-bens/cc-port/releases/download/v#{version}/cc-port-with-logo_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "28208b812af83c7a1c5cb0d527a460a976b649830b068dd8c3b6178c71ab01b8"
      url "https://github.com/it-bens/cc-port/releases/download/v#{version}/cc-port-with-logo_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "af2edb2e0f02eef4cc41073b314d1605929b6c63146e2af4332fbc9f085e71de"
      url "https://github.com/it-bens/cc-port/releases/download/v#{version}/cc-port-with-logo_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "2d21a3281e199ca66c931b9457e5edc0f08604fd9ef595844267eff9bca32ab9"
      url "https://github.com/it-bens/cc-port/releases/download/v#{version}/cc-port-with-logo_linux_arm64.tar.gz"
    end
  end

  name "cc-port-with-logo"
  desc "Claude Code project portability tool (with crane logo)"
  homepage "https://github.com/it-bens/cc-port"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cc-port-with-logo"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/cc-port-with-logo"] if OS.mac?
  end

  zap trash: [
      "~/.claude/.cc-port.lock",
    ]

end
