# This file was generated by GoReleaser. DO NOT EDIT.
cask "cc-port" do
  version "0.5.1"

  on_macos do
    on_intel do
      sha256 "4c5257daa46008a0c5c45cca765f258cc976f6b591a3f044c47cbfc7a44bab20"
      url "https://github.com/it-bens/cc-port/releases/download/v#{version}/cc-port_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "3dd0172068ee054fcbbc62ccb2c596554843cd739d9b86c157363e47bc5f3ae3"
      url "https://github.com/it-bens/cc-port/releases/download/v#{version}/cc-port_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "42b5f5b9eaac944194a2119bf2ef6a98de3e96489b61756fd624322ab270c28a"
      url "https://github.com/it-bens/cc-port/releases/download/v#{version}/cc-port_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "f805fb001411522561974ff9d545856c7db7dc69d1fdd2fd17b5a554193646ff"
      url "https://github.com/it-bens/cc-port/releases/download/v#{version}/cc-port_linux_arm64.tar.gz"
    end
  end

  name "cc-port"
  desc "Claude Code project portability tool"
  homepage "https://github.com/it-bens/cc-port"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cc-port"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/cc-port"] if OS.mac?
  end

  zap trash: [
      "~/.claude/.cc-port.lock",
    ]

end
