# This file was generated by GoReleaser. DO NOT EDIT.
cask "cc-port-with-logo" do
  version "0.3.0"

  on_macos do
    on_intel do
      sha256 "b34c4858f2dd0e26ac98936abbca35e80c952d156b5e6fc96ab3f36f79ba25a5"
      url "https://github.com/it-bens/cc-port/releases/download/v#{version}/cc-port-with-logo_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "2276e672fd07781569a1a48ee17e007d2b2f948ac4d6194c68c72e7c639ef660"
      url "https://github.com/it-bens/cc-port/releases/download/v#{version}/cc-port-with-logo_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "073f4f5f061bef21236831de19aae50a282ff389d916cc4d9754640adb2146f7"
      url "https://github.com/it-bens/cc-port/releases/download/v#{version}/cc-port-with-logo_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "b32050f49f4a7393818407b9ad1c343311d1089e1149e11ce1989748f3d17dbf"
      url "https://github.com/it-bens/cc-port/releases/download/v#{version}/cc-port-with-logo_linux_arm64.tar.gz"
    end
  end

  name "cc-port-with-logo"
  desc "Claude Code project portability tool (with crane logo)"
  homepage "https://github.com/it-bens/cc-port"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cc-port-with-logo"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/cc-port-with-logo"] if OS.mac?
  end

  zap trash: [
      "~/.claude/.cc-port.lock",
    ]

end
