# This file was generated by GoReleaser. DO NOT EDIT.
cask "cc-port-with-logo" do
  version "0.5.0"

  on_macos do
    on_intel do
      sha256 "45d62a4399c753d3d7b34d09724035d3ed9b837d6ee4b5a46558e9b57be5db75"
      url "https://github.com/it-bens/cc-port/releases/download/v#{version}/cc-port-with-logo_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "52153b9bfb586ce267897df7e014b6b1f7af42830c3577bca07e31c58b444479"
      url "https://github.com/it-bens/cc-port/releases/download/v#{version}/cc-port-with-logo_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "dd27bc799cc9e91c1291a3193acf093f973ae750a6dcd4e1ae3b5a005267d2c8"
      url "https://github.com/it-bens/cc-port/releases/download/v#{version}/cc-port-with-logo_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "e2de3f7bc5a59ecc08109161279beb20cbb87de271fabc2dca7dd5721ee68eb7"
      url "https://github.com/it-bens/cc-port/releases/download/v#{version}/cc-port-with-logo_linux_arm64.tar.gz"
    end
  end

  name "cc-port-with-logo"
  desc "Claude Code project portability tool (with crane logo)"
  homepage "https://github.com/it-bens/cc-port"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cc-port-with-logo"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/cc-port-with-logo"] if OS.mac?
  end

  zap trash: [
      "~/.claude/.cc-port.lock",
    ]

end
