# This file was generated by GoReleaser. DO NOT EDIT.
cask "cc-port" do
  version "0.6.0"

  on_macos do
    on_intel do
      sha256 "82b1740269b7260f8a85e79b7f4576f492c0ec1f7a0466eef3bf8e1891f36b51"
      url "https://github.com/it-bens/cc-port/releases/download/v#{version}/cc-port_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "255907e40c98e4989061d3cae21f0342fa164e1e1eaceb147d6ac68b0c9c2524"
      url "https://github.com/it-bens/cc-port/releases/download/v#{version}/cc-port_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "1bb05cf820b68872e0d2505168f4bc72d235fd64e893530c92790f7ae1a8ea51"
      url "https://github.com/it-bens/cc-port/releases/download/v#{version}/cc-port_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "13dd61f1c88fa83cc6576522c6dd4d45f6f6f182904248ea72531b66af649b46"
      url "https://github.com/it-bens/cc-port/releases/download/v#{version}/cc-port_linux_arm64.tar.gz"
    end
  end

  name "cc-port"
  desc "Claude Code project portability tool"
  homepage "https://github.com/it-bens/cc-port"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cc-port"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/cc-port"] if OS.mac?
  end

  zap trash: [
      "~/.claude/.cc-port.lock",
    ]

end
