# This file was generated by GoReleaser. DO NOT EDIT.
cask "cc-port" do
  version "0.7.0"

  on_macos do
    on_intel do
      sha256 "614a839a40b0d7847851bcf544bc6d846fbfd8ec0de23aebe013ff5f5837af3a"
      url "https://github.com/it-bens/cc-port/releases/download/v#{version}/cc-port_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "b2f0a2f864ca8391ad6be990601a64d636f9cfaecd5a176223b4db761e4b6ced"
      url "https://github.com/it-bens/cc-port/releases/download/v#{version}/cc-port_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "568adfcb9d6aa65f2ffc0b001e6ce0602d9c28b6794a18598e9985c1e4164e2b"
      url "https://github.com/it-bens/cc-port/releases/download/v#{version}/cc-port_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "b6599262e38020f842154733642b15f8fc0b4756f056a48f1d1a58a17787ac0b"
      url "https://github.com/it-bens/cc-port/releases/download/v#{version}/cc-port_linux_arm64.tar.gz"
    end
  end

  name "cc-port"
  desc "Claude Code project portability tool"
  homepage "https://github.com/it-bens/cc-port"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cc-port"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/cc-port"] if OS.mac?
  end

  zap trash: [
      "~/.claude/.cc-port.lock",
    ]

end
