# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CcPort < Formula
  desc "Claude Code project portability tool"
  homepage "https://github.com/it-bens/cc-port"
  version "0.0.1-test"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/it-bens/cc-port/releases/download/v0.0.1-test/cc-port_darwin_amd64.tar.gz"
      sha256 "03013815827fdc15c96c0764241f124a51e1838502c02ec03cf0ec867595e0ce"

      define_method(:install) do
        bin.install "cc-port"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/it-bens/cc-port/releases/download/v0.0.1-test/cc-port_darwin_arm64.tar.gz"
      sha256 "0d244324720bc7209e1777b392e5b23ae8006cfdd9908542f7e64f3a2373454b"

      define_method(:install) do
        bin.install "cc-port"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/it-bens/cc-port/releases/download/v0.0.1-test/cc-port_linux_amd64.tar.gz"
      sha256 "b799d23f6425ad4b8cd5a168bf275c07fd6c7a601e2a9e241a3a375a993102a0"
      define_method(:install) do
        bin.install "cc-port"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/it-bens/cc-port/releases/download/v0.0.1-test/cc-port_linux_arm64.tar.gz"
      sha256 "bb8e7f62abef2d41c8f291d32233b33f0684439925c3f6509efc5fc27172e62a"
      define_method(:install) do
        bin.install "cc-port"
      end
    end
  end

  test do
    system "#{bin}/cc-port", "version"
  end
end
